//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int MaDH { get; set; }
        public int MaCTSP { get; set; }
        public int SoLuong { get; set; }
    
        public virtual CHITIETSP CHITIETSP { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
