//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSP
    {
        public int ID { get; set; }
        public int MaSP { get; set; }
        public int MaSize { get; set; }
        public int MaMau { get; set; }
        public int SoLuong { get; set; }
    
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual SIZE SIZE { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
