//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETSP()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.KHOHANGs = new HashSet<KHOHANG>();
        }
    
        public int Id { get; set; }
        public int MaSP { get; set; }
        public int MaSize { get; set; }
        public int MaMau { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual SIZE SIZE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOHANG> KHOHANGs { get; set; }
    }
}
