//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int MaDH { get; set; }
        public int MaKH { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public string DiaChiGiao { get; set; }
        public decimal TongTien { get; set; }
        public string ThanhToan { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual CHITIETDONHANG CHITIETDONHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
