//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOHANG
    {
        public int Id { get; set; }
        public int MaCT { get; set; }
        public int SoLuongBan { get; set; }
        public int SoLuongCon { get; set; }
    
        public virtual CHITIETSP CHITIETSP { get; set; }
    }
}
